from supabase import create_client, Client


SUPABASE_URL = "https://bmimvypwjbitykmqmmuv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtaW12eXB3amJpdHlrbXFtbXV2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTk1MTAyMSwiZXhwIjoyMDg1NTI3MDIxfQ.ierbVEzOReeCIPq4eZAH3wmgHUJrPKalRlDpnziB2bM"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)